MVC/Models/ErrorViewModel.cs
namespace MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

MVC/Models/ToDo.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace MVC.Models
{

		public class ToDo
		{
			public int Id { get; set; }

        [Required(ErrorMessage ="ToDo Name is required")]

        public  string name { get; set; }

            public bool isFinished { get; set; }

            public string? descriotion { get; set; }

        public DateTime CreatedDate { get; set; }

    }
}

MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult Contact()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

MVC/Controllers/ToDoController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using MVC.Data;

namespace MVC.Controllers
{
	public class ToDoController : Controller 
	{
		private readonly ApplicationDbContext _context;
        public ToDoController(ApplicationDbContext context)
		{
			_context = context;
		}

		public IActionResult Index()
		{
			var todo = _context.ToDos.ToList();

			return View(todo);
		}
	}
}

MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVC/Views/Home/ToDo.cshtml
@model List<ToDo>

<div>
    <a asp-controller="ToDo" asp-action="create" class="btn btn-primary"> Create ToDo</a>
</div>

@if (Model.Count() > 0)
{
        <table class="table table-hover table-striped">
            <thead>
                <th>
                    <td>
                        id
                    </td>
                    <td>Name</td>
                    <td>date</td>
            <td> Description </td>
                    <td>Is Finished</td>

                </th>
            </thead>

            <tbody>
                @foreach (var item in Model)
{
                        <tr>
                            <td> @item.Id</td>
                            <td> @item.name</td>
                            <td> @item.CreatedDate.Month</td>
                            <td> @item.isFinished</td>
                            <td>
                                <a asp-controller="ToDo" asp-action="Update" class="btn btn-info"> Update </a>
                            </td>
                            <td>
                                <a asp-controller="ToDo" asp-action="Delete" class="btn btn-danger"> Delete </a>
                            </td>

                        </tr>
}
            </tbody>

        </table>
}
else
{
        <div class="mt-4 bg-light">
            <h3>no Todos are avaliable</h3>

        </div>
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDo" asp-action="Index">My ToDo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>